#pragma once

enum States
{
	OVERWORLD,
	OVERWORLD_MENU
};

#define STARTING_MAP	10
#define STARTING_X		0
#define STARTING_Y		0

#define VIEWPORT_WIDTH	20
#define VIEWPORT_HEIGHT	18

#define CONNECTION_NORTH	0
#define CONNECTION_SOUTH	1
#define CONNECTION_WEST		2
#define CONNECTION_EAST		3

#define WATER_TILE 20